version: '3.8'

services:
  # Eureka Server
  eureka-server:
    container_name: eos-eureka-server-prod
    build:
      context: ./eureka-server
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8761:8761"
    networks:
      - eos_network

  # MySQL Database
  mysql-db:
    container_name: eos-mysql-prod
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eos_prod
      MYSQL_USER: eos_prod
      MYSQL_PASSWORD: eos_prod
    volumes:
      - "./Scripts/setup-eos.sql:/docker-entrypoint-initdb.d/setup-eos.sql"
    ports:
      - "3307:3306"
    networks:
      - eos_network

  # Order Service
  order-service:
    build:
      context: ./order-service
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - eureka-server
      - mysql-db
    command: ["./wait-for-it.sh", "mysql-db:3306", "--timeout=60", "--", "java", "-jar", "order-service-0.0.1-SNAPSHOT.jar"]
    networks:
      - eos_network

  # Report Service
  report-service:
    build:
      context: ./report-service
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - eureka-server
      - mysql-db
    command: ["./wait-for-it.sh", "mysql-db:3306" , "--timeout=60", "--", "java", "-jar", "report-service-0.0.1-SNAPSHOT.jar"]
    networks:
      - eos_network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - eureka-server
      - mysql-db
      - order-service
      - report-service
    command: ["./wait-for-it.sh", "order-service:8081" , "--timeout=100", "--", "java", "-jar", "api-gateway-0.0.1-SNAPSHOT.jar"]
    networks:
      - eos_network
networks:
  eos_network:
    driver: bridge